In [1]:
# import libraries
import numpy as np

In [2]:
# Create arrays

TD = np.array([[2,3,0,3,7],
              [0,5,5,0,3],
              [5,0,7,3,3],
              [3,1,0,9,9],
              [0,0,7,1,3],
              [6,9,4,6,0]])

L = np.array([5,2,3,6,4,3])


## 1. Matrix P(T,D)

P(T,D) = TDᵢⱼ/∑TDᵢ


In [12]:
n_docs = TD.shape[1]
P_TD_uniform = (TD / (TD.sum(axis=0, keepdims=True)/0.2))
print(P_TD_uniform)

[[0.025      0.03333333 0.         0.02727273 0.056     ]
 [0.         0.05555556 0.04347826 0.         0.024     ]
 [0.0625     0.         0.06086957 0.02727273 0.024     ]
 [0.0375     0.01111111 0.         0.08181818 0.072     ]
 [0.         0.         0.06086957 0.00909091 0.024     ]
 [0.075      0.1        0.03478261 0.05454545 0.        ]]


In [11]:
P_TD_uniform.sum(axis=0)

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [ ]:
### wrong
# Caclulate probability for each value in TD

prob_TD = TD/TD.sum()

print(prob_TD)

## 2. Matrix P(T|D)

$$
P(t_i \mid d_j) = \frac{\text{# times } t_i \text{ appears in } d_j}{\text{total number of terms in } d_j} = \frac{TD_{i,j}}{\sum_k TD_{k,j}}
$$

In [13]:
prob_T_given_D = P_TD_uniform / P_TD_uniform.sum(axis=0, keepdims=True)

print(prob_T_given_D)

[[0.125      0.16666667 0.         0.13636364 0.28      ]
 [0.         0.27777778 0.2173913  0.         0.12      ]
 [0.3125     0.         0.30434783 0.13636364 0.12      ]
 [0.1875     0.05555556 0.         0.40909091 0.36      ]
 [0.         0.         0.30434783 0.04545455 0.12      ]
 [0.375      0.5        0.17391304 0.27272727 0.        ]]


### wrong

By conditional probability we know that

P(T|D) = P(T∩D)/P(D)

Given the sum of each column on the matrix is the total of occurences of T on given D.



In [ ]:
### wrong
prob_T_given_D = prob_TD/prob_TD.sum(axis=0)
print(prob_T_given_D)

## 3. Matrix P(D|T)


In [ ]:
P_T = P_TD_uniform.sum(axis=1, keepdims=True)
P_D_given_T = P_TD_uniform / P_T

print(P_D_given_T)

[[0.17654612 0.23539482 0.         0.19259576 0.3954633 ]
 [0.         0.45154704 0.35338464 0.         0.19506832]
 [0.35787437 0.         0.34853851 0.15616336 0.13742376]
 [0.18524987 0.05488885 0.         0.40418153 0.35567975]
 [0.         0.         0.64782097 0.09675248 0.25542655]
 [0.28373832 0.37831776 0.13158879 0.20635514 0.        ]]



### wrong

By conditional probability we know that

P(D|T) = P(D∩T)/P(T)

Given the sum of each column on the matrix is the total of occurences of T.


In [ ]:
prob_D_given_T = prob_TD/prob_TD.sum(axis=1,keepdims=True)
print(prob_D_given_T)

[[0.13333333 0.2        0.         0.2        0.46666667]
 [0.         0.38461538 0.38461538 0.         0.23076923]
 [0.27777778 0.         0.38888889 0.16666667 0.16666667]
 [0.13636364 0.04545455 0.         0.40909091 0.40909091]
 [0.         0.         0.63636364 0.09090909 0.27272727]
 [0.24       0.36       0.16       0.24       0.        ]]


## 4. Vector P(D)

In [ ]:
P_D = 1/TD.shape[1]
print(P_D)

0.2




### wrong
Probability vector of D.

In [ ]:
P_D = prob_TD.sum(axis=0)
print(P_D)

[0.15384615 0.17307692 0.22115385 0.21153846 0.24038462]


## 5. Vector P(T)

In [15]:
P_T = P_TD_uniform.sum(axis=1, keepdims=True)
print(P_T)

[[0.14160606]
 [0.12303382]
 [0.17464229]
 [0.20242929]
 [0.09396047]
 [0.26432806]]



### wrong
Probability vector of T.

In [ ]:
P_T = prob_TD.sum(axis=1, keepdims=True)
print(P_T)

[[0.14423077]
 [0.125     ]
 [0.17307692]
 [0.21153846]
 [0.10576923]
 [0.24038462]]


## 6. E[l]

To calclulate the expected value we use the dot product.

E[l] = ∑P(Tᵢ)⋅L

In [18]:
E_l = np.dot(P_T.T,L)
print(E_l)

[3.86142666]


## 7. Variance var(l)

Using the formula:

Var(l) = 𝔼[(l - 𝔼[l])²]

This can be rewriten as:

Var(l) = 𝔼[l²] - (𝔼[l])²

In [19]:
E_lpow2 = np.dot(P_T.T,L**2)
var_l = E_lpow2 - E_l**2
print(var_l)

[1.86322628]
